---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- vendor/**/*
